@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/user/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/user/suggestions
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile/63b97acac6c51acc8e6d0457
Content-Type: application/json
Accept: application/json
withCredentials: true

#'/user/profile/posts/:username/:userId/:uId'
###
GET {{baseUrl}}/{{urlPath}}/user/profile/posts/Testemai/63b54a0218af1cdc2b1294fa/0
Content-Type: application/json
Accept: application/json
withCredentials: true

#'/user/profile/search/:query
###
GET {{baseUrl}}/{{urlPath}}/user/profile/search/test
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/change-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "currentPassword": "test1234",
  "newPassword": "test123",
  "confirmPassword": "test123"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/basic-info
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "quote": "life is dead",
  "work": "SDE",
  "school": "NEU",
  "location": "seattle"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/social-links
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "facebook": "facebook",
  "instagram": "instagram",
  "twitter": "twitter",
  "youtube": "youtube"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/settings
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "messages": false,
  "reactions": false,
  "comments": true,
  "follows": true
}
